version: '3.9'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: sarymov/diploma:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: sarymov/frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - web


  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./foodgramproject.crt:/etc/nginx/foodgramproject.crt
      - ./foodgramproject.key:/etc/nginx/foodgramproject.key
      - ../docs/:/usr/share/nginx/html/api/docs
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/

    depends_on:
      - web
      - frontend
    restart: always

volumes:
  static_value:
  media_value:
  db_postgres:
